# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: communication.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='communication.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x63ommunication.proto\" \n\x0c\x64\x61ta_request\x12\x10\n\x08\x62\x36\x34image\x18\x01 \x01(\x0c\"=\n\ndata_reply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07\x63lasses\x18\x02 \x03(\t\x12\r\n\x05\x62oxes\x18\x03 \x01(\x0c\x32\x31\n\x04\x64\x61ta\x12)\n\trecognize\x12\r.data_request\x1a\x0b.data_reply\"\x00\x62\x06proto3'
)




_DATA_REQUEST = _descriptor.Descriptor(
  name='data_request',
  full_name='data_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='b64image', full_name='data_request.b64image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=55,
)


_DATA_REPLY = _descriptor.Descriptor(
  name='data_reply',
  full_name='data_reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='data_reply.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='classes', full_name='data_reply.classes', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='boxes', full_name='data_reply.boxes', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=118,
)

DESCRIPTOR.message_types_by_name['data_request'] = _DATA_REQUEST
DESCRIPTOR.message_types_by_name['data_reply'] = _DATA_REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

data_request = _reflection.GeneratedProtocolMessageType('data_request', (_message.Message,), {
  'DESCRIPTOR' : _DATA_REQUEST,
  '__module__' : 'communication_pb2'
  # @@protoc_insertion_point(class_scope:data_request)
  })
_sym_db.RegisterMessage(data_request)

data_reply = _reflection.GeneratedProtocolMessageType('data_reply', (_message.Message,), {
  'DESCRIPTOR' : _DATA_REPLY,
  '__module__' : 'communication_pb2'
  # @@protoc_insertion_point(class_scope:data_reply)
  })
_sym_db.RegisterMessage(data_reply)



_DATA = _descriptor.ServiceDescriptor(
  name='data',
  full_name='data',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=120,
  serialized_end=169,
  methods=[
  _descriptor.MethodDescriptor(
    name='recognize',
    full_name='data.recognize',
    index=0,
    containing_service=None,
    input_type=_DATA_REQUEST,
    output_type=_DATA_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATA)

DESCRIPTOR.services_by_name['data'] = _DATA

# @@protoc_insertion_point(module_scope)
