# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import communication_pb2 as communication__pb2


class dataStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.recognize = channel.unary_unary(
                '/data/recognize',
                request_serializer=communication__pb2.data_request.SerializeToString,
                response_deserializer=communication__pb2.data_reply.FromString,
                )


class dataServicer(object):
    """Missing associated documentation comment in .proto file."""

    def recognize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_dataServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'recognize': grpc.unary_unary_rpc_method_handler(
                    servicer.recognize,
                    request_deserializer=communication__pb2.data_request.FromString,
                    response_serializer=communication__pb2.data_reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'data', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class data(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def recognize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/data/recognize',
            communication__pb2.data_request.SerializeToString,
            communication__pb2.data_reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
